FROM mysql:latest
LABEL maintainer="Gabriel Bento"

ENV MYSQL_ROOT_PASSWORD=${MY_ROOT_PASSWORD}
ENV MYSQL_DATABASE=${MYSQL_DATABASE}
ENV MYSQL_USER=${MYSQL_USER}
ENV MYSQL_PASSWORD=${MYSQL_PASSWORD}

EXPOSE 3306

VOLUME /opt/mysql_proposal /var/lib/mysql